# Generated by Django 4.2.5 on 2023-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellevoapp', '0002_remove_conductor_id_alter_conductor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserWithConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
