# Generated by Django 4.2.5 on 2023-11-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellevoapp', '0003_customuserwithconductor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserWithConductor',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='usuario',
            new_name='id',
        ),
    ]
