# Generated by Django 4.2.5 on 2023-11-07 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellevoapp', '0004_delete_customuserwithconductor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='usuario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conductor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
