# Generated by Django 4.2.5 on 2023-11-07 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellevoapp', '0006_vehiculo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_viaje', models.CharField(max_length=255)),
                ('destino_viaje', models.CharField(max_length=255)),
                ('tarifa', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=255)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tellevoapp.conductor')),
                ('usuario_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
