# Generated by Django 4.2.2 on 2023-12-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellevoapp', '0007_viaje_delete_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='destino_viaje',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='inicio_viaje',
        ),
        migrations.AddField(
            model_name='conductor',
            name='nombre_completo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_lat',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_lon',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='inicio_lat',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='inicio_lon',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
